### ISSUE TITLE
Search input is not full

### ISSUE THREAD

**Issue by adiletelf** [rohitmultani/Fake-Store#1]
<img width="298" alt="image" src="https://user-images.githubusercontent.com/74559101/180739979-c2b1d2c9-b716-4433-ac2b-c8c3986e9511.png">
<img width="296" alt="image" src="https://user-images.githubusercontent.com/74559101/180740004-8ba70d07-4322-4e44-90d9-9fdceb1222a1.png">

## Problem
Input tag is smaller than enclosed div - even though I click at div the input tag is not triggered and that's annoying.

## Solution
Make the input tag the full size of enclosed div.

**Comment by rohitmultani** [comment]
Thanks for figuring this out.
